name: zweidenker_heinzelmen
version: 2.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  app_tracking_transparency: ^2.0.6+1
  flutter:
    sdk: flutter
  flutter_web_browser: ^0.17.3
  package_info_plus: ^9.0.0
  universal_platform: ^1.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  url_launcher_platform_interface: ^2.3.2

flutter:

